import json
import argparse
from pathlib import Path

def assemble_raw_markdown(json_path: str, output_md_path: str = None):
    """
    Reads a _raw_pages.json file generated by pymupdf4llm
    and assembles it into a single .md file, bypassing the LLM completely.
    """
    json_file = Path(json_path)
    
    if not json_file.exists():
        print(f"Error: Could not find {json_file}")
        return

    if output_md_path is None:
        # Default output path: same directory, just replacing _raw_pages.json with .md
        output_file = json_file.parent / json_file.name.replace("_raw_pages.json", ".md")
    else:
        output_file = Path(output_md_path)

    print(f"Reading raw pages from {json_file.name}...")
    
    with open(json_file, 'r', encoding='utf-8') as f:
        pages = json.load(f)

    # pymupdf4llm stores the markdown for each page in the 'text' key
    assembled_text = ""
    for idx, page in enumerate(pages):
        text = page.get("text", "")
        if text:
            # Add a subtle page break marker for debugging
            # assembled_text += f"\n\n<!-- PAGE {idx + 1} -->\n\n"
            assembled_text += text
            assembled_text += f"\n\n"

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(assembled_text)

    print(f"Successfully assembled {len(pages)} pages into:")
    print(f" -> {output_file}")
    print("You can now run the ETL pipeline and it will automatically skip Stage 1!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Assemble raw markdown from _raw_pages.json")
    parser.add_argument("json_path", help="Path to the _raw_pages.json file")
    parser.add_argument("--out", help="Optional: Path to output .md file", default=None)
    
    args = parser.parse_args()
    assemble_raw_markdown(args.json_path, args.out)
